language: cpp

os: osx

osx_image: xcode10.3

git:
  depth: false
  quiet: true

addons:
  homebrew:
    brewfile: true
    # TODO: Remove the `update` line once this PR has been released:
    # https://github.com/travis-ci/packer-templates-mac/pull/13
    update: true

script:
  - cd build
  - cmake -DBINARY_RELEASE=ON ..
  - sudo cmake --build . --target package -j $(sysctl -n hw.physicalcpu)

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "build/devilutionx.dmg"
  skip_cleanup: true
  on:
    tags: true
