version: 1.1.{build}

pull_requests:
  do_not_increment_build_number: true
environment:
  matrix:

  - job_name: windows
    appveyor_build_worker_image: Visual Studio 2022

for:
  -
    matrix:
      only:
        - job_name: windows

    cache:
      - '%LOCALAPPDATA%\vcpkg\archives'
      - c:\tools\vcpkg\installed\

    install:
      - if not exist C:\Tools\vcpkg mkdir C:\Tools\vcpkg
      - cd C:\Tools\vcpkg
      - git pull
      - .\bootstrap-vcpkg.bat
      - cd %APPVEYOR_BUILD_FOLDER%

    before_build:
      - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
      - cmake -G "Ninja" -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DDISCORD_INTEGRATION=ON -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake .

    build_script:
      - cmake --build build --parallel 4

    artifacts:
      - path: build\devilutionx.exe
        name: devilutionx.exe

  -
    matrix:
      only:
        - job_name: uwp

    before_build:
      - cd %APPVEYOR_BUILD_FOLDER%\Packaging\xbox-one
      - if exist ..\..\build rd /s /q ..\..\build

    build_script:
      - build.bat

    after_build:
      - cd %APPVEYOR_BUILD_FOLDER%

    artifacts:
      - path: devilutionx.zip
        name: devilutionx.zip
