version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform: x86

before_build:
    - cmake -G "Visual Studio 15 2017 x86" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: minimal
