---
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
comment: false
coverage:
  range: "45...85"
  status:
    project:
      default:
        target: 0%
        threshold: 0.02%
    patch: false
ignore:
  - "3rdParty"
  - "test"
flag_management:
  default_rules:
    carryforward: false
...
