version: 2
jobs:
  linux_x86_64_test:
    docker:
      - image: debian:stable
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y g++ libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev git cmake libsodium-dev libgtest-dev lcov curl
      - run: cmake -S. -Bbuild -DRUN_TESTS=ON
      - run: cmake --build build -j 2
      - run: build/devilutionx
      - run: cmake --build build -j 2 --target test
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  testflow:
    jobs:
      - linux_x86_64_test
