version: 2
jobs:
  amigaos-m68k:
    docker:
      - image: amigadev/crosstools:m68k-amigaos-gcc10
    working_directory: ~/repo
    steps:
      - checkout
      - run: Packaging/amiga/prep.sh
      - run: cmake -S. -Bbuild -DM68K_CPU=68040 -DM68K_FPU=hard -DM68K_COMMON="-s -fbbb=- -ffast-math -O2"
      - run: cd build && make -j2
      - store_artifacts: {path: ./build/devilutionx, destination: devilutionx_m68k}

workflows:
  version: 2
  testflow:
    jobs:
      - amigaos-m68k
