version: 2
jobs:
  linux_x86_64:
    docker:
      - image: debian:stretch-backports
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo deb http://deb.debian.org/debian stretch-backports-sloppy main >> /etc/apt/sources.list.d/debian-backports.list
      - run: apt update -y
      - run: apt install -y g++ libsdl2-dev libsdl2-ttf-dev git rpm wget
      - run: apt install -y -t 'stretch-backports*' cmake libsodium-dev libpng-dev
      - run: cmake -S. -Bbuild .. -DNIGHTLY_BUILD=ON -DCMAKE_INSTALL_PREFIX=/usr
      - run: cmake --build build -j 2 --target package
      - store_artifacts: {path: ./build/devilutionx, destination: devilutionx_linux_x86_64}
      - run: Packaging/nix/LinuxReleasePackaging.sh
      - run: Packaging/nix/AppImage.sh
      - store_artifacts: {path: ./devilutionx.appimage, destination: devilutionx_linux_x86_64.appimage}
      - store_artifacts: {path: ./devilutionx.tar.xz, destination: devilutionx_linux_x86_64.tar.xz}
  linux_x86_64_test:
    docker:
      - image: debian:testing
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y cmake curl g++ git lcov libgtest-dev libgmock-dev libfmt-dev libsdl2-dev libsdl2-ttf-dev libsodium-dev libpng-dev
      - run: cmake -S. -Bbuild -DRUN_TESTS=ON -DENABLE_CODECOVERAGE=ON
      - run: cmake --build build -j 2
      - run: cmake --build build -j 2 --target test
      - run: bash <(curl -s https://codecov.io/bash)
    environment:
      CTEST_OUTPUT_ON_FAILURE: 1
  amigaos-m68k:
    docker:
      - image: amigadev/crosstools:m68k-amigaos
    working_directory: ~/repo
    steps:
      - checkout
      - run: Packaging/amiga/prep.sh
      - run: PKG_CONFIG_PATH=/opt/m68k-amigaos/lib/pkgconfig/:/opt/m68k-amigaos/share/pkgconfig/ cmake -S. -Bbuild -DM68K_CPU=68040 -DM68K_FPU=hard -DM68K_COMMON="-s -ffast-math -O3 -noixemul -D__BIG_ENDIAN__ -D__AMIGA__ -fpermissive" ..
      - run: cd build && make -j2
      - store_artifacts: {path: ./build/devilutionx, destination: devilutionx_m68k}

workflows:
  version: 2
  testflow:
    jobs:
      - linux_x86_64
      - linux_x86_64_test
      - amigaos-m68k
