---
name: Nintendo 3DS

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends --no-install-suggests \
            ffmpeg \
            gettext

      - name: Get external dependencies
        run: |
          wget https://github.com/diasurgical/bannertool/releases/download/1.2.0/bannertool.zip
          unzip -j "bannertool.zip" "linux-x86_64/bannertool" -d "/opt/devkitpro/tools/bin"
          wget https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-ubuntu_x86_64.zip
          unzip "makerom-v0.18-ubuntu_x86_64.zip" "makerom" -d "/opt/devkitpro/tools/bin"
          chmod a+x /opt/devkitpro/tools/bin/makerom

      - name: Configure CMake
        run: |
          cmake -S. -Bbuild -GNinja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/3DS.cmake

      - name: Build DevilutionX
        run: cmake --build build

      - name: Upload Package
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: devilutionx.3dsx/cia
          path: |
            ./build/devilutionx.3dsx
            ./build/devilutionx.cia

      - name: Update Release 3dsx
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: devilutionx-3ds.3dsx
          file: ./build/devilutionx.3dsx
          overwrite: true

      - name: Update Release cia
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: devilutionx-3ds.cia
          file: ./build/devilutionx.cia
          overwrite: true
...
