name: Android

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
  release:
    types: [published]
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gettext
      run: sudo apt-get update && sudo apt-get install -y gettext

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Cache CMake build folder
      uses: actions/cache@v3
      with:
        path: android-project/app/.cxx
        key: ${{ github.workflow }}-v1-${{ github.sha }}
        restore-keys: ${{ github.workflow }}-v1-

    - name: Build
      working-directory: ${{github.workspace}}/android-project
      shell: bash
      run: ./gradlew ${{github.event_name == 'release' && 'assembleDebug' || 'assembleRelease'}}

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v3
      with:
        name: devilutionx-${{github.event_name == 'release' && 'release' || 'debug'}}.apk
        path: android-project/app/build/outputs/apk/${{github.event_name == 'release' && 'release' || 'debug'}}/app-${{github.event_name == 'release' && 'release' || 'debug'}}.apk

    - name: Update Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      uses: svenstaro/upload-release-action@v2
      with:
        file: android-project/app/build/outputs/apk/release/app-release.apk
        asset_name: devilutionx-android.apk
        overwrite: true
