name: Linux_x86_64_SDL1

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: >
        sudo apt update &&
        sudo apt install -y cmake file g++ git libfmt-dev libsdl-dev libsdl-ttf2.0-dev libsodium-dev rpm

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -S. -Bbuild .. -DNIGHTLY_BUILD=ON -DUSE_SDL1=ON

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build build -j $(nproc) --target package

    - name: Upload-Executable
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx_linux_x86_64_SDL1
        path: build/devilutionx

    - name: Package
      run: Packaging/nix/LinuxReleasePackaging.sh

    - name: Upload-Package
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx_linux_x86_64_SDL1.tar.xz
        path: devilutionx.tar.xz
