name: macOS

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: brew bundle install

    - name: Cache CMake build folder
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ github.workflow }}-v1-${{ github.sha }}
        restore-keys: ${{ github.workflow }}-v1-

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CMAKE_BUILD_TYPE: ${{github.event_name == 'release' && 'Release' || 'RelWithDebInfo'}}
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DBUILD_TESTING=OFF \
          -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          -DMACOSX_STANDALONE_APP_BUNDLE=ON -DDISCORD_INTEGRATION=ON && \
        cmake --build build -j $(sysctl -n hw.physicalcpu) --target package && \
        mv build/devilutionx.dmg build/devilutionx-universal-macOS.dmg

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v3
      with:
        name: devilutionx-universal-macOS.dmg
        path: build/devilutionx-universal-macOS.dmg

    - name: Update Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      uses: svenstaro/upload-release-action@v2
      with:
        file: build/devilutionx-universal-macOS.dmg
        overwrite: true

    - name: Clean up artifacts
      run: rm -rf build/_CPack_Packages build/*.dmg
