---
name: OpenDingux Release Build

on:  # yamllint disable-line rule:truthy
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gcw0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Build Environment
        run: |
          apt-get update
          apt-get install -y \
            curl \
            cmake \
            git \
            squashfs-tools
          curl -L https://github.com/OpenDingux/buildroot/releases/download/od-2022.09.22/opendingux-gcw0-toolchain.2022-09-22.tar.xz -o gcw0-toolchain.tar.xz
          sudo mkdir -p /opt/gcw0-toolchain
          chown -R "${USER}:" /opt/gcw0-toolchain
          tar -C /opt -xf gcw0-toolchain.tar.xz
          cd /opt/gcw0-toolchain
          ./relocate-sdk.sh

      - name: Build
        working-directory: ${{github.workspace}}
        shell: bash
        run: Packaging/OpenDingux/build.sh rg350
        env:
          TOOLCHAIN: /opt/gcw0-toolchain

      - name: Upload-Package
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: devilutionx-rg350.opk.zip
          path: build-rg350/devilutionx-rg350.opk

      - name: Update Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: "build-rg350/devilutionx-rg350.opk"
          overwrite: true

  lepus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Build Environment
        run: |
          apt-get update
          apt-get install -y \
            curl \
            cmake \
            git \
            squashfs-tools
          curl -L https://github.com/OpenDingux/buildroot/releases/download/od-2022.09.22/opendingux-lepus-toolchain.2022-09-22.tar.xz -o lepus-toolchain.tar.xz
          mkdir -p /opt/lepus-toolchain
          chown -R "${USER}:" /opt/lepus-toolchain
          tar -C /opt -xf lepus-toolchain.tar.xz
          cd /opt/lepus-toolchain
          ./relocate-sdk.sh

      - name: Build
        working-directory: ${{github.workspace}}
        shell: bash
        run: Packaging/OpenDingux/build.sh lepus
        env:
          TOOLCHAIN: /opt/lepus-toolchain

      - name: Upload-Package
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: devilutionx-lepus.opk.zip
          path: build-lepus/devilutionx-lepus.opk

      - name: Update Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: "build-lepus/devilutionx-lepus.opk"
          overwrite: true
...
