---
name: PS4

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ps4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Build Environment
        run: |
          apt-get update &&
          apt-get install -y \
            wget \
            cmake \
            git \
            gettext \
            smpq &&
          wget https://github.com/PacBrew/pacbrew-pacman/releases/download/v1.1/pacbrew-pacman-1.1.deb &&
          dpkg -i pacbrew-pacman-1.1.deb && sudo pacbrew-pacman -Sy &&
          pacbrew-pacman --noconfirm -S ps4-openorbis ps4-openorbis-portlibs &&
          echo "#include <endian.h>" | tee /opt/pacbrew/ps4/openorbis/include/sys/endian.h

      - name: Build
        working-directory: ${{github.workspace}}
        shell: bash
        run: Packaging/ps4/build.sh

      - name: Upload-Package
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: devilutionx-ps4.pkg
          path: build-ps4/devilutionx.pkg

      - name: Update Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: devilutionx-ps4.pkg
          file: build-ps4/devilutionx.pkg
          overwrite: true
...
